language: node_js

node_js:
  - "12.7.0"

os:
  - osx

osx_image: xcode9.3

cache:
  yarn: true

install:
  - yarn

script:
  - yarn distlinux
  - ls -la dist

deploy:
  provider: releases
  user: "wznpp1"
  password: "lzhrwwc1"
  file:
    - "dist/Mellow*.AppImage"
  skip_cleanup: true
  on:
    tags: true
